### ISSUE TITLE
[Home] corregir texto en 3 bloque de fotos

### ISSUE THREAD

**Issue by davidquiroga** [lindacastillor/noreste#2]
Al editarlo en wp y actualizarlo se ve de esta forma, eliminar espacio y un scroll.

![screen shot 2016-02-22 at 10 47 40](https://cloud.githubusercontent.com/assets/14933452/13225278/bd9601d4-d951-11e5-891b-0b6613e6ddc4.png)

**Comment by davidquiroga** [comment]
También cambiar el estilo del texto en hipervínculo a como se tenía en las maquetas principales:
Cambiar como este:
![diseno](https://cloud.githubusercontent.com/assets/14933452/13225639/48576b5e-d953-11e5-9d47-ee5f8440aa43.png)
actualmente:
![wp](https://cloud.githubusercontent.com/assets/14933452/13225638/4856251e-d953-11e5-92ed-21734a7ea357.png)

**Comment by lindacastillor** [comment]
- Para que se vea bien la palabra "Nosotros", hay que revisar que tipo de formato que se utiliza actualmente.
- Tratar de utilizar el drop down de la parte izquierda, ese "botón" sirve para agregar un enlace a todo el bloque, PERO si llegarán a insertar un enlace en la caja de texto se puede romper el código ocasionando el bug del primer screen shot que pusiste.
  ![screen-shot-2016-03-04-at-11 26 17-am](https://cloud.githubusercontent.com/assets/12926376/13534916/14a538ec-e1fd-11e5-96ce-6ff8af74c2e6.png)
