### ISSUE TITLE
[Bloque Contacto] cambiar color de gris

### ISSUE THREAD

**Issue by davidquiroga** [lindacastillor/noreste#6]
El gris de fondo debe ser el mismo que el del bloque del footer donde está Facebook e Instagram de fondo e igual para todas las secciones en donde aparezca. 

![screen shot 2016-02-22 at 17 21 07](https://cloud.githubusercontent.com/assets/14933452/13236224/b93bae5e-d988-11e5-8318-4f016371475a.png)

**Comment by lindacastillor** [comment]
Ya lo cambié al gris mas obscuro.
